= Audiothek-Feed

This project provides Atom feeds for shows in the https://www.ardaudiothek.de/[ARD-Audiothek].

After starting the software, go to http://0.0.0.0:3000 and enter the link to a show or its id (e.g. https://www.ardaudiothek.de/sendung/levels-und-soundtracks/12642475/, the id is the last part of the url, so _12642475_).

You will then get the url of the generated Atom feed which you can use with your podcatcher like any other feed.

Alternatively, you can build the feed url on your own like this: http://0.0.0.0:3000/feed/your_show_id_here

== Building/Running

The project consists of two Parts: The Rust backend and the HTML/HTMX frontend.

=== Using Docker

[source, bash]
----
docker run -p 3000:3000 ghcr.io/tufteddeer/audiothek-feed:0.1.0
----

=== Using Nix

Both parts are built using a https://nixos.org/[Nix] Flake that provides a package for each one, where the backend package depends on the frontend.
The result of the frontend build is embedded in the Rust binary at compile time, which locates the artifacts using the `FRONTEND_DIR` environment variable.

[source, bash]
----
nix run
----

=== Using Cargo 

The `devShell` sets `FRONTEND_DIR` to the `frontend` source directory so `cargo run` works as well. If you are not using a Nix shell, you must set `FRONTEND_DIR` manually.

[source, bash]
----
# in ./frontend
npm install
npm run build

# in the root directory
cargo run
----